### ISSUE TITLE
Components Roadmap

### ISSUE THREAD

**Issue by n7best** [weui/react-weui#35]
## WeUI 0.3.0 Components
- [x] Actionsheet
- [x] Article
- [x] Button
- [x] Cell
- [x] Dialog
  - [x] Alert
  - [x] Confirm
- [x] Form
  - [x] Label - [0.3 beta]
  - [x] Input  -[0.3 beta] 
  - [x] Textarea - [0.3 beta] 
  - [x] Radio [0.3 beta]
  - [x] Checkbox [0.3 beta]
  - [x] Select [0.3 beta]
  - [x] Switch - [0.3 beta]
  - [x] Uploader - [0.3 beta]
- [x] Grid
- [x] Msg Page
- [x] Toast
- [x] Progress
- [x] Icon
  - [ ] Add custom class #63
## WeUI 0.4.0
- [x] Tabbar [0.3 beta] 
- [x] Navbar [0.3 beta] 
- [x] Panel - [0.3 beta] 
  - [x] MediaBox - [0.3 beta] 
- [x] Search Bar [0.3 beta] 
## Other
- [ ] Gallery
- [ ] Swiper / Slider
- [ ] Pull To Refresh
- [ ] Infinity Scroll
- [ ] Router
- [ ] Card

**Comment by progrape** [comment]
补充一下 Card 组件~

**Comment by hongkang** [comment]
为什么组件没有持续更新啊，check 什么的都用不上。是不是太忙了。。。

**Comment by n7best** [comment]
@hongkang 有的 会陆续更新

**Comment by cipchk** [comment]
能否在示例中更新已经开发好的部分 Form 组件呢？

**Comment by n7best** [comment]
@cipchk 在develop分支里头事例都已经更新好的。预览效果在合并master后更新。

**Comment by n7best** [comment]
Moved to Projects Tab
